### ISSUE TITLE
Packaging this repo as a provider

### ISSUE THREAD

**Issue by kasey** [crossplane-contrib/provider-terraform-vsphere#3]
We need to pull in the generic crossplane build script and ensure we can run a release process resulting in a tagged docker image. We'll need to figure out how we want to package the terraform provider binary, the easiest solution potentially being to package a simple `main.tf` for the purpose of `terraform init` in a build container, and then find the binary in the resulting `.terraform` directory. Alternatively we could hook into the same library functions that the cli uses to download providers at build time.

**Comment by hasheddan** [comment]
Have a branch in progress for this 👍

**Comment by grantgumina** [comment]
@hasheddan can we close this if this is done?

**Comment by hasheddan** [comment]
@grantgumina yep! Thanks for the catch!
